[package]
name = "tiny-url"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }
tokio = {version = "1.41.0", features = ["full"]}
warp = "0.3.7"